development:
  :address: smtp.gmail.com
  :port: 25
  :authentication: plain
  :user_name: jsomers@gmail.com
  :password: 1TwoMany!
production:
  :address: smtp.gmail.com
  :port: 25
  :authentication: plain
  :user_name: jsomers@gmail.com
  :password: 1TwoMany!